#!/bin/bash

export DISPLAY=:0.0

function program(){
 echo "********* GENERATING CRYPTO KEYS" >> /tmp/safecast.log
 /home/safecast/bunniegeiger/crypto/genkeys >> /tmp/safecast.log 2>&1
 UUID=`grep UUID /tmp/safecast.log | awk -F' ' '{ print $2 }'`
 echo "********* PROGRAMMING FIRMWARE" >> /tmp/safecast.log
 /home/safecast/bunniegeiger/firmware_loader/pkload -f /home/safecast/bunniegeiger/firmware/safecast_latest.bin -p /tmp/secblock.bin >> /tmp/safecast.log
# /home/safecast/bunniegeiger/firmware_loader/pkload -f /tmp/secblock.bin >> /tmp/safecast.log
 modprobe usbserial
 modprobe ftdi_sio
 sleep 5
 echo "********* IDLE" >> /tmp/safecast.log
 sync
 cp -f /tmp/safecast.log /home/safecast/logs/$UUID/
 sync
 rmdir /tmp/safecast-semaphore
} 

if mkdir /tmp/safecast-semaphore
then
  echo " " > /tmp/safecast.log  # some newlines
  echo " " >> /tmp/safecast.log
  echo " " >> /tmp/safecast.log
  echo "********* STARTED" >> /tmp/safecast.log
  rmmod ftdi_sio
  rmmod usbserial
  program &
fi 
