#!/bin/sh

### to get (fake) randomness quickly
### sudo apt-get install rng-tools
### sudo echo "HRNGDEVICE=/dev/urandom" >> /etc/default/rng-tools
### sudo /etc/init.d/rng-tools start

TMPPATH=/tmp
ABSPATH=/home/safecast/bunniegeiger/crypto

echo $TMPPATH

# start a find to "create" randomness
find / -type f 2> /dev/null | xargs grep makerandomdata > /dev/null 2>&1 &
sleep 2

# clean up any files from a previous run
rm -f $TMPPATH/pubring.gpg
rm -f $TMPPATH/secring.gpg
rm -f $TMPPATH/secblock.bin
rm -f $TMPPATH/pubkey.txt

gpg --no-options --batch --no-default-keyring --keyring $TMPPATH/pubring.gpg --secret-keyring $TMPPATH/secring.gpg --gen-key $ABSPATH/gen-key-config 
gpg --keyring $TMPPATH/pubring.gpg --export -a signing-keys@safecast.org > $TMPPATH/pubkey.txt

killall find
killall xargs
killall grep

# hard-code path...well, this script should *only* be run on one computer anyways.
sudo $ABSPATH/catkeys $TMPPATH/secring.gpg $TMPPATH/pubkey.txt $TMPPATH/secblock.bin
#./catkeys

echo "genkeys attempt finished"

