/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you are using AIX */
/* #undef AIX */

/* Define to 1 if you want to include the C++ code */
/* #undef CPPGLUE */

/* Define to 1 if you are using Cygwin */
// #define CYGWIN 1

/* Define to 1 if you are using Darwin/MacOS X */
/* #undef DARWIN */

/* Define to 1 if you want to enable asynchronous I/O support */
/* #undef ENABLE_AIO */

/* Define to 1 if you want to enable multithread support */
/* #define ENABLE_THREADS 1 */

/* Define to 1 if you want to enable thread-local-storage support */
/* #define ENABLE_THREAD_LOCAL_STORAGE 0 */

/* Define to 1 if you are using FreeBSD */
/* #undef FREEBSD */

/* Define to 1 if you have the <aio.h> header file. */
/* #undef HAVE_AIO_H */

/* Define to 1 if you have the <asm/byteorder.h> header file. */
#define HAVE_ASM_BYTEORDER_H 1

/* Define to 1 if you have the <assert.h> header file. */
#define HAVE_ASSERT_H 1

/* Define to 1 if you have the <ctype.h> header file. */
#define HAVE_CTYPE_H 1

/* Define to 1 if your system has device /dev/audio */
/* #undef HAVE_DEV_AUDIO */

/* Define to 1 if your system has device /dev/dsp */
/* #undef HAVE_DEV_DSP */

/* Define to 1 if your system has device /dev/random */
/* #undef HAVE_DEV_RANDOM */

/* Define to 1 if your system has device /dev/tty */
/* #undef HAVE_DEV_TTY */

/* Define to 1 if your system has device /dev/urandom */
/* #define HAVE_DEV_URANDOM 1 */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <endian.h> header file. */
#define HAVE_ENDIAN_H 1

/* Define to 1 if you have the <errno.h> header file. */
/* #define HAVE_ERRNO_H 1 */

/* Define to 1 if you have the <fcntl.h> header file. */
/* #define HAVE_FCNTL_H 1 */

/* Define to 1 if you have the `gethrtime' function. */
/* #undef HAVE_GETHRTIME */

/* . */
#define HAVE_GETTIMEOFDAY 1

/* . */
#define HAVE_INLINE 1

/* */
#define HAVE_INT64_T 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `mtmalloc' library (-lmtmalloc). */
/* #undef HAVE_LIBMTMALLOC */

/* Define to 1 if you have the `winmm' library (-lwinmm). */
#define HAVE_LIBWINMM 1

/* */
/* #define HAVE_LONG_LONG 1 */

/* Define to 1 if you have the <malloc.h> header file. */
#define HAVE_MALLOC_H 1

/* Define to 1 if you have the `memcmp' function. */
#define HAVE_MEMCMP 1

/* Define to 1 if you have the `memmove' function. */
#define HAVE_MEMMOVE 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* Define to 1 if you have the <mtmalloc.h> header file. */
/* #undef HAVE_MTMALLOC_H */

/* Define to 1 if you have the <pthread.h> header file. */
/* #define HAVE_PTHREAD_H 1 */

/* Define to 1 if you have the <semaphore.h> header file. */
/* #define HAVE_SEMAPHORE_H 1 */

/* Define to 1 if `stat' has the bug that it succeeds when given the
   zero-length file name argument. */
/* #undef HAVE_STAT_EMPTY_STRING_BUG */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcspn' function. */
#define HAVE_STRCSPN 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strspn' function. */
#define HAVE_STRSPN 1

/* Define to 1 if you have the <synch.h> header file. */
/* #undef HAVE_SYNCH_H */

/* Define to 1 if you have the <sys/audioio.h> header file. */
/* #undef HAVE_SYS_AUDIOIO_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/mman.h> header file. */
#define HAVE_SYS_MMAN_H 1

/* Define to 1 if you have the <sys/soundcard.h> header file. */
#define HAVE_SYS_SOUNDCARD_H 1

/* . */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* . */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <termios.h> header file. */
#define HAVE_TERMIOS_H 1

/* Define to 1 if you have the <termio.h> header file. */
#define HAVE_TERMIO_H 1

/* Define to 1 if you have the <thread.h> header file. */
/* #undef HAVE_THREAD_H */

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* */
/*#define HAVE_UINT64_T 1*/

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* */
/*#define HAVE_UNSIGNED_LONG_LONG 1 */

/* Define to 1 if you are using HPUX */
/* #undef HPUX */

/* Define to 1 if you want to include the Java code */
/*#define JAVAGLUE 1 */

/* Define to 1 if you are using GNU/Linux */
/*#define LINUX 1 */
/* #undef LINUX */

/* Define to 1 if `lstat' dereferences a symlink specified with a trailing
   slash. */
#define LSTAT_FOLLOWS_SLASHED_SYMLINK 1

/* Define to 1 if you are using NetBSD */
/* #undef NETBSD */

/* Define to 1 if you are using OpenBSD */
/* #undef OPENBSD */

/* Define to 1 if you are using OSF */
/* #undef OSF */

/* Name of package */
#define PACKAGE "beecrypt"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "bob.deblier@telenet.be"

/* Define to the full name of this package. */
#define PACKAGE_NAME "beecrypt"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "beecrypt 4.1.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "beecrypt"

/* Define to the version of this package. */
#define PACKAGE_VERSION "4.1.2"

/* Define to 1 if you want to include the Python code */
#define PYTHONGLUE 1

/* Define to 1 if you are using QNX */
/* #undef QNX */

/* Define to 1 if you are using SCO Unix */
/* #undef SCO_UNIX */

/* The size of a `int', as computed by sizeof. */
/* #undef SIZEOF_INT */

/* The size of a `long', as computed by sizeof. */
/* #undef SIZEOF_LONG */

/* The size of a `long long', as computed by sizeof. */
/* #undef SIZEOF_LONG_LONG */

/* The size of a `short', as computed by sizeof. */
/* #undef SIZEOF_SHORT */

/* The size of a `signed char', as computed by sizeof. */
/* #undef SIZEOF_SIGNED_CHAR */

/* The size of a `size_t', as computed by sizeof. */
#define SIZEOF_SIZE_T 4

/* The size of a `unsigned char', as computed by sizeof. */
/* #undef SIZEOF_UNSIGNED_CHAR */

/* The size of a `unsigned int', as computed by sizeof. */
/* #undef SIZEOF_UNSIGNED_INT */

/* The size of a `unsigned long', as computed by sizeof. */
#define SIZEOF_UNSIGNED_LONG 4

/* The size of a `unsigned long long', as computed by sizeof. */
/* #undef SIZEOF_UNSIGNED_LONG_LONG */

/* The size of a `unsigned short', as computed by sizeof. */
/* #undef SIZEOF_UNSIGNED_SHORT */

/* Define to 1 if you are using Solaris */
/* #undef SOLARIS */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Version number of package */
#define VERSION "4.1.2"


//#ifndef WIN32
// #define WIN32 1
//#endif
#ifndef LINUX
#define LINUX 1
#endif


/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Define to 1 if on AIX 3.
   System headers sometimes define this.
   We just want to avoid a redefinition error message.  */
#ifndef _ALL_SOURCE
/* # undef _ALL_SOURCE */
#endif

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */


#if ENABLE_THREADS
# ifndef _REENTRANT
#  define _REENTRANT
# endif
#if LINUX
#  define _LIBC_REENTRANT
# endif
#else
# ifdef _REENTRANT
/* #  undef _REENTRANT */
# endif
#endif



#if !ENABLE_THREAD_LOCAL_STORAGE
# define __thread
#endif

